# Generated by Django 5.2 on 2025-04-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
