# Generated by Django 5.2 on 2025-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('want', '観たい'), ('watched', '観た'), ('cannot', '観れない')], default='want', max_length=10),
        ),
        migrations.AddField(
            model_name='log',
            name='times',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
