# Generated by Django 5.2 on 2025-04-22 08:19


from django.db import migrations, models

def dedupe(apps, schema_editor):
    Log = apps.get_model('core', 'Log')
    dup = (Log.objects.values('user_id', 'stage_id')
                    .annotate(cnt=models.Count('id'))
                    .filter(cnt__gt=1))
    for d in dup:
        # 同じ user+stage の 2 件目以降を全部消す
        (Log.objects.filter(user_id=d['user_id'], stage_id=d['stage_id'])
                     .order_by('-id')[1:]
                     .delete())

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_stage_poster_url"),  # 直前のファイル
    ]

    operations = [
        migrations.RunPython(dedupe, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="log",
            constraint=models.UniqueConstraint(
                fields=["user", "stage"],
                name="unique_user_stage",
            ),
        ),
    ]


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_stage_poster_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='log',
            constraint=models.UniqueConstraint(fields=('user', 'stage'), name='unique_user_stage'),
        ),
    ]
