# Generated by Django 5.2 on 2025-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stage_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='staff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
