# Generated by Django 5.2 on 2025-04-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=30)),
                ('color', models.CharField(default='#666', max_length=7)),
                ('icon_svg', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='members', to='core.badge'),
        ),
    ]
