# Generated by Django 5.2 on 2025-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stage_cast_stage_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='poster',
        ),
        migrations.AddField(
            model_name='stage',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
