# Generated by Django 5.2 on 2025-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_badge_profile_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='badges',
        ),
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, choices=[('', '— 未設定 —'), ('actor', '俳優部'), ('staff', '制作部'), ('producer', '製作部')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
