# Generated by Django 5.2 on 2025-04-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['open_date']},
        ),
        migrations.AddField(
            model_name='stage',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
