# Generated by Django 5.2 on 2025-04-29 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_stage_options_stage_close_date_stage_open_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('category', models.CharField(max_length=40)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('map_url', models.URLField(blank=True, max_length=400)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('sponsor_tier', models.CharField(choices=[('free', '自動取得'), ('ally', '協力店'), ('sponsor', 'スポンサー')], default='free', max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('memo', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-rating'],
                'unique_together': {('lat', 'lng', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TheaterShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.PositiveIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_shops', to='core.shop')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_shops', to='core.theater')),
            ],
            options={
                'unique_together': {('theater', 'shop')},
            },
        ),
    ]
