# Generated by Django 5.2 on 2025-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_shop_theatershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
