# Generated by Django 5.2 on 2025-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_theater_lat_theater_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
