# Generated by Django 5.2 on 2025-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shop_distance_m_shop_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
