# Generated by Django 5.2 on 2025-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_shop_lat_alter_shop_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatershop',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
