# Generated by Django 5.2 on 2025-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_theatershop_distance_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='sponsor_tier',
            field=models.CharField(choices=[('free', '自動取得'), ('partner', '協力店'), ('sponsor', 'スポンサー')], default='free', max_length=10),
        ),
    ]
