# Generated by Django 5.2 on 2025-04-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_shop_sponsor_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
