# Generated by Django 5.2 on 2025-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_shop_map_url_alter_shop_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(unique=True)),
                ('source', models.CharField(max_length=50)),
                ('pub_at', models.DateTimeField()),
                ('image', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-pub_at'],
            },
        ),
    ]
