# Generated by Django 4.2.26 on 2025-12-02 06:10

import cloudinary.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text='マチネ／ソワレ／特別公演 など', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('area', models.CharField(blank=True, help_text='メインのエリア（例：東京／名古屋／大阪）', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('area_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='エリアタグ（例：["新宿", "小劇場"]）', size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('troupe', models.CharField(blank=True, help_text='劇団・ユニット名', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='main image')),
                ('status', models.CharField(choices=[('PENDING', '審査中'), ('APPROVED', '公開'), ('REJECTED', '非公開')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('main_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='works', to='api.actor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_works', to=settings.AUTH_USER_MODEL)),
                ('main_theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.theater')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='作品タグ（会話劇、一人芝居、SF など）※カンマ区切り', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ViewingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(help_text='観た日')),
                ('seat', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, help_text='1〜5の評価', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.performance')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='ログ用タグ（泣いた、初見、千秋楽など）※カンマ区切り', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_logs', to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.work')),
            ],
            options={
                'ordering': ['-watched_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='本公演／地方公演などのラベル', max_length=200)),
                ('area', models.CharField(blank=True, help_text='エリア（例：東京／名古屋／大阪）', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('theater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.theater')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.work')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='api.run'),
        ),
        migrations.AddField(
            model_name='performance',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.theater'),
        ),
    ]
