# Generated by Django 4.2.26 on 2025-12-02 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewinglog',
            options={'ordering': ['-watched_at', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='viewinglog',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='viewinglog',
            name='watched_date',
        ),
        migrations.AddField(
            model_name='viewinglog',
            name='run',
            field=models.ForeignKey(blank=True, help_text='どの公演ブロック（東京公演/大阪公演等）で観たか（任意）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.run'),
        ),
        migrations.AddField(
            model_name='viewinglog',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='観劇日時'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('DRAFT', '仮作品（作成者のみ）'), ('PENDING', '審査中'), ('APPROVED', '公開')], default='APPROVED', help_text='DRAFT: 作成者のみ閲覧可 / PENDING: 要確認 / APPROVED: 公開', max_length=20),
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
