# Generated by Django 5.2 on 2025-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_icon_customuser_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icon',
        ),
        migrations.AddField(
            model_name='customuser',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
